#!/bin/sh
# Regenerate requirements.txt: the exact pinned closure the image installs with --no-deps.
#
# Resolves pyproject.toml's loose ranges from scratch, drops the transitive packages
# cadquery declares but spur never imports, proves what is left can still build a gear
# and answer an HTTP request, and freezes that.
set -eu
cd "$(dirname "$0")/.."
PLATFORM="${PLATFORM:-linux/amd64}"

# Keeping these costs ~550 MB and buys nothing: VTK viewers, DXF export, the assembly
# solver's plotting, matplotlib. What must stay, and why:
#   vtk       OCP links libvtkWrappingPythonCore -- OCP will not import without it
#   casadi nlopt ezdxf pyparsing multimethod runtype   cadquery imports these eagerly
#   idna      anyio needs it, and only an HTTP request finds that out, which is why
#             docker/smoke.py drives the ASGI app instead of just calling export()
PRUNE="trame trame-client trame-common trame-components trame-server trame-vtk
trame-vuetify wslink numba llvmlite matplotlib contourpy cycler kiwisolver pillow
scipy aiohttp aiosignal frozenlist multidict yarl propcache attrs msgpack"

docker build --platform "$PLATFORM" -q -t spur:resolve - >/dev/null <<'DOCKER'
FROM python:3.12-slim-bookworm
RUN apt-get update \
 && apt-get install -y --no-install-recommends libgl1 libx11-6 libexpat1 \
 && rm -rf /var/lib/apt/lists/*
DOCKER

frozen=$(docker run --rm --platform "$PLATFORM" -v "$PWD:/src:ro" -e PRUNE="$PRUNE" \
  spur:resolve sh -c '
    set -eu
    pip install -q --no-cache-dir /src
    pip uninstall -y -q $PRUNE >/dev/null 2>&1 || true
    python /src/docker/smoke.py >&2
    pip freeze | grep -v "^spur" | sort')

cat > requirements.txt <<HEADER
# The exact package closure the Docker image installs, with --no-deps.
#
# Generated by docker/refresh-requirements.sh -- do not edit one line at a time: with
# --no-deps pip will not tell you when a hand-bumped version breaks the closure.
# pyproject.toml keeps loose ranges for installing into your own environment.
HEADER
printf '%s\n' "$frozen" >> requirements.txt
echo "wrote requirements.txt ($(grep -c '==' requirements.txt) packages)" >&2
echo "now verify both architectures:" >&2
echo "  docker build --platform linux/amd64 -t spur:check . && docker build --platform linux/arm64 -t spur:check ." >&2
